site_name: Teknik Donanım ve Oyun Optimizasyonu
site_url: https://pseo-optimizasyon.pages.dev
site_description: Donanım bileşenleri, Linux sistemleri ve rekabetçi oyunlar için maksimum performans optimizasyon rehberleri.
site_author: Kadir Akdeniz

theme:
  name: material
  custom_dir: overrides
  language: tr
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Koyu temaya geç
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Açık temaya geç
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true

markdown_extensions:
  - meta
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
